name: CI
on:
  push:
    branches:
      - master
      - release-[6-9].*
  pull_request:
    branches-ignore: release-[0-5].*
  pull_request_target:
    branches-ignore: release-[0-5].*
  workflow_dispatch:
env:
  DOTNET_NOLOGO: true
jobs:
  build:
    name: CI-${{ matrix.os }}-${{ matrix.engine }}
    if:
      (github.event_name == 'pull_request_target' && github.event.pull_request.user.login == 'dependabot[bot]') ||
      (github.event_name == 'pull_request' && github.event.pull_request.user.login != 'dependabot[bot]') ||
      github.event_name == 'push' || github.event_name == 'workflow_dispatch'
    runs-on: ${{ matrix. os }}
    strategy:
      matrix:
        os: [ windows-2019, ubuntu-20.04 ]
        engine:
          - MsSql
          #- Oracle
          - MySql
          - PostgreSql
      fail-fast: false
    steps:
      - name: Check for secrets
        env:
          SECRETS_AVAILABLE: ${{ secrets.SECRETS_AVAILABLE }}
        shell: pwsh
        run: exit $(If ($env:SECRETS_AVAILABLE -eq 'true') { 0 } Else { 1 })
      - name: Checkout
        if: github.event_name != 'pull_request_target'
        uses: actions/checkout@v2.3.4
        with:
          fetch-depth: 0
      - name: Checkout for Dependabot
        if: github.event_name == 'pull_request_target'
        uses: actions/checkout@v2.3.4
        with:
          ref: "refs/pull/${{ github.event.number }}/merge"
          fetch-depth: 0
      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v1.9.0
        with:
          dotnet-version: |
            5.0.x
            3.1.x
      - name: Build
        run: dotnet build src --configuration Release
      - name: Upload packages
        uses: actions/upload-artifact@v2.2.4
        with:
          name: NuGet packages
          path: nugets/
          retention-days: 7
      - name: Azure login
        uses: azure/login@v1.3.0
        with:
          creds: ${{ secrets.AZURE_ACI_CREDENTIALS }}
      - name: Setup SQL Server
        if: matrix.engine == 'MsSql'
        uses: Particular/install-sql-server-action@v1.0.0
        with:
          connection-string-env-var: SQLServerConnectionString
          catalog: nservicebus
      - name: Setup PostgreSql
        id: setup-postgresql
        if: matrix.engine == 'PostgreSql'
        shell: pwsh
        run: |
          echo "Getting the Azure region in which this workflow is running..."
          $hostInfo = curl -H Metadata:true --noproxy "*" "http://169.254.169.254/metadata/instance?api-version=2021-02-01" | ConvertFrom-Json
          $region = $hostInfo.compute.location
          echo "Actions agent running in Azure region $region"

          $name = "postgres-$(Get-Random)"
          $packageTag = "Package=SqlPersistence"
          $runnerOsTag = "RunnerOS=$($Env:RUNNER_OS)"
          $dateTag = "Created=$(Get-Date -Format "yyyy-MM-dd")"

          $password = [guid]::NewGuid().ToString("n")
          echo "::add-mask::$password"

          echo "Creating PostgreSQL container $name (This can take a while)"
          $details = az container create --image postgres:14 --name $name --location $region --dns-name-label $name --resource-group GitHubActions-RG --cpu 2 --memory 8 --ports 5432 --ip-address public --environment-variables POSTGRES_PASSWORD="$password" | ConvertFrom-Json
          echo "::set-output name=name::$name"

          echo "Tagging container"
          $ignore = az tag create --resource-id $details.id --tags $packageTag $runnerOsTag $dateTag

          $fqdn = $details.ipAddress.fqdn
          echo "::add-mask::$fqdn"

          $connectionString = "User ID=postgres;Password=$password;Host=$fqdn;Port=5432;Database=postgres;"
          echo "PostgreSqlConnectionString=$connectionString" | Out-File -FilePath $Env:GITHUB_ENV -Encoding utf-8 -Append

          $env:PGPASSWORD = $password

          # psql not in PATH on Windows
          if ($Env:RUNNER_OS -eq 'Windows') {
            $Env:PATH = $Env:PATH + ';' + $Env:PGBIN
            echo "New Path"
            echo $Env:PATH
          }

          for ($i = 0; $i -lt 24; $i++) { ## 2 minute timeout
            echo "Checking for PostgreSQL connectivity $($i+1)/30..."
            $ignore = psql --host $fqdn --username=postgres --list
            if ($?) {
              echo "Connection successful"
              break;
            }
            sleep 5
          }

      - name: Setup MySQL
        id: setup-mysql
        if: matrix.engine == 'MySql'
        shell: pwsh
        run: |
          echo "Getting the Azure region in which this workflow is running..."
          $hostInfo = curl -H Metadata:true --noproxy "*" "http://169.254.169.254/metadata/instance?api-version=2021-02-01" | ConvertFrom-Json
          $region = $hostInfo.compute.location
          echo "Actions agent running in Azure region $region"

          $name = "mysql-$(Get-Random)"
          $packageTag = "Package=SqlPersistence"
          $runnerOsTag = "RunnerOS=$($Env:RUNNER_OS)"
          $dateTag = "Created=$(Get-Date -Format "yyyy-MM-dd")"

          $password = [guid]::NewGuid().ToString("n")
          echo "::add-mask::$password"

          echo "Creating MySQL container $name (This can take a while)"
          $details = az container create --image mysql:8 --name $name --location $region --dns-name-label $name --resource-group GitHubActions-RG --cpu 2 --memory 8 --ports 3306 --ip-address public --environment-variables MYSQL_ROOT_PASSWORD="$password" MYSQL_USER=particular MYSQL_PASSWORD="$password" MYSQL_DATABASE=nservicebus | ConvertFrom-Json
          echo "::set-output name=name::$name"

          echo "Tagging container"
          $ignore = az tag create --resource-id $details.id --tags $packageTag $runnerOsTag $dateTag

          $fqdn = $details.ipAddress.fqdn
          echo "::add-mask::$fqdn"

          $connectionString = "server=$fqdn;user=particular;database=nservicebus;port=3306;password=$password;AllowUserVariables=True;AutoEnlist=false;Connect Timeout=120;SslMode=Required"
          echo "MySQLConnectionString=$connectionString" | Out-File -FilePath $Env:GITHUB_ENV -Encoding utf-8 -Append

          $passwordArg = "-p$password"
          for ($i = 0; $i -lt 24; $i++) { ## 2 minute timeout
            echo "Checking for MySQL connectivity $($i+1)/30..."
            $ignore = mysql -h $fqdn -u particular $passwordArg -e "show databases;"
            if ($?) {
              echo "Connection successful"
              break;
            }
            sleep 5
          }

      - name: Setup Oracle
        id: setup-oracle
        if: matrix.engine == 'Oracle'
        shell: pwsh
        run: |
          echo "Getting the Azure region in which this workflow is running..."
          $hostInfo = curl -H Metadata:true --noproxy "*" "http://169.254.169.254/metadata/instance?api-version=2021-02-01" | ConvertFrom-Json
          $region = $hostInfo.compute.location
          echo "Actions agent running in Azure region $region"

          $name = "oracle-$(Get-Random)"
          $packageTag = "Package=SqlPersistence"
          $runnerOsTag = "RunnerOS=$($Env:RUNNER_OS)"
          $dateTag = "Created=$(Get-Date -Format "yyyy-MM-dd")"

          $password = [guid]::NewGuid().ToString("n")
          echo "::add-mask::$password"

          echo "Creating Oracle container $name (This can take a while)"
          $details = az container create --image particularci.azurecr.io/oracledb:21.3 --registry-username particularci --registry-password ${{ secrets.AZURE_CONTAINER_REGISTRY_PASSWORD }} --name $name --location $region --dns-name-label $name --resource-group GitHubActions-RG --cpu 2 --memory 8 --ports 1521 5500 --ip-address public --environment-variables ORACLE_PWD="$password" ORACLE_CHARACTERSET=AL32UTF8 | ConvertFrom-Json
          echo "::set-output name=name::$name"

          echo "Tagging container"
          $ignore = az tag create --resource-id $details.id --tags $packageTag $runnerOsTag $dateTag

          $fqdn = $details.ipAddress.fqdn
          echo "::add-mask::$fqdn"

          $connectionString = "User Id=system;Password=$password;Data Source=$fqdn:1521/XEPDB1;"
          echo "OracleConnectionString=$connectionString" | Out-File -FilePath $Env:GITHUB_ENV -Encoding utf-8 -Append

          echo "Sleeping for 20s to wait for Oracle to start up. Should replace this with a script or tool in the future."
          sleep 20

      - name: Run tests
        uses: Particular/run-tests-action@v1.0.0
      - name: Teardown infrastructure
        if: ${{ always() }}
        shell: pwsh
        run: |
          if ('${{ matrix.engine }}' -eq 'PostgreSql') {
            echo "Removing container ${{ steps.setup-postgresql.outputs.name }}"
            $ignore = az container delete --resource-group GitHubActions-RG --name ${{ steps.setup-postgresql.outputs.name }} --yes
            echo "Removal complete"
          }

          if ('${{ matrix.engine }}' -eq 'MySql') {
            echo "Removing container ${{ steps.setup-mysql.outputs.name }}"
            $ignore = az container delete --resource-group GitHubActions-RG --name ${{ steps.setup-mysql.outputs.name }} --yes
            echo "Removal complete"
          }

          # if ('${{ matrix.engine }}' -eq 'Oracle') {
          # echo "Removing container ${{ steps.setup-oracle.outputs.name }}"
          #   $ignore = az container delete --resource-group GitHubActions-RG --name ${{ steps.setup-oracle.outputs.name }} --yes
          #  echo "Removal complete"
          # }
  oracle-windows:
    name: CI-windows-2019-Oracle
    if:
      (github.event_name == 'pull_request_target' && github.event.pull_request.user.login == 'dependabot[bot]') ||
      (github.event_name == 'pull_request' && github.event.pull_request.user.login != 'dependabot[bot]') ||
      github.event_name == 'push' || github.event_name == 'workflow_dispatch'
    runs-on: [self-hosted, windows, oracle]
    steps:
      - name: Check for secrets
        env:
          SECRETS_AVAILABLE: ${{ secrets.SECRETS_AVAILABLE }}
        shell: pwsh
        run: exit $(If ($env:SECRETS_AVAILABLE -eq 'true') { 0 } Else { 1 })
      - name: Checkout
        if: github.event_name != 'pull_request_target'
        uses: actions/checkout@v2.3.4
        with:
          fetch-depth: 0
      - name: Checkout for Dependabot
        if: github.event_name == 'pull_request_target'
        uses: actions/checkout@v2.3.4
        with:
          ref: "refs/pull/${{ github.event.number }}/merge"
          fetch-depth: 0
      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v1.9.0
        with:
          dotnet-version: |
            5.0.x
            3.1.x
      - name: Build
        run: dotnet build src --configuration Release
      - name: Run tests
        uses: Particular/run-tests-action@v1.0.0
        env:
          OracleConnectionString: "User Id=c##particular;Password=Welcome1;Data Source=127.0.0.1:1521/XEPDB1;Enlist=dynamic"
          OracleConnectionString_Particular2: "User Id=c##particular2;Password=Welcome1;Data Source=127.0.0.1:1521/XEPDB1;Enlist=dynamic"
  oracle-linux:
    name: CI-ubuntu-20.04-Oracle
    if:
      (github.event_name == 'pull_request_target' && github.event.pull_request.user.login == 'dependabot[bot]') ||
      (github.event_name == 'pull_request' && github.event.pull_request.user.login != 'dependabot[bot]') ||
      github.event_name == 'push' || github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-20.04
    steps:
      - name: Check for secrets
        env:
          SECRETS_AVAILABLE: ${{ secrets.SECRETS_AVAILABLE }}
        shell: pwsh
        run: exit $(If ($env:SECRETS_AVAILABLE -eq 'true') { 0 } Else { 1 })
      - name: Checkout
        if: github.event_name != 'pull_request_target'
        uses: actions/checkout@v2.3.4
        with:
          fetch-depth: 0
      - name: Checkout for Dependabot
        if: github.event_name == 'pull_request_target'
        uses: actions/checkout@v2.3.4
        with:
          ref: "refs/pull/${{ github.event.number }}/merge"
          fetch-depth: 0
      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v1.9.0
        with:
          dotnet-version: |
            5.0.x
            3.1.x
      - name: Setup Oracle
        shell: bash
        run: |
          docker run -d -p 1521:1521 -e ORACLE_PASSWORD=Welcome1 gvenzl/oracle-xe
          sleep 20
      - name: Build
        run: dotnet build src --configuration Release
      - name: Run tests
        uses: Particular/run-tests-action@v1.0.0
        env:
          OracleConnectionString: "OracleConnectionString=Data Source=(DESCRIPTION=(ADDRESS_LIST = (ADDRESS = (PROTOCOL = TCP)(HOST = 127.0.0.1)(PORT = 1521)))(CONNECT_DATA = (SERVER = DEDICATED)(SERVICE_NAME = XE)));User Id=SYSTEM; Password=Welcome1; Enlist=dynamic"

